### ISSUE TITLE
Curious about COPY here

### ISSUE THREAD

**Issue by rengler33** [max-pfeiffer/uvicorn-poetry#1]
Hey Max, I'm curious about the COPY choice here

https://github.com/max-pfeiffer/uvicorn-poetry/blob/fb0fdf7691e92ebdc8261ad38096d0d8161ecbbe/examples/fast_api_multistage_build/Dockerfile#L51

```
FROM base-image as production-image

COPY --from=base-image $VIRTUAL_ENVIRONMENT_PATH $VIRTUAL_ENVIRONMENT_PATH
```

Is there a reason to `COPY --from=base-image` when the image itself is built `FROM base-image`?

**Comment by max-pfeiffer** [comment]
Hi Robert,
good point: I was already looking at that and wanted to optimise the production-image in my next release. Here I wanted to do something like this:
```
FROM python:3.9.8-slim-bullseye as production-image
```
Reason is that you want your image to be as slim as possible. This way you leave out the Poetry installation that you don't need to have in your production image.
Regards, Max
